version: "3"

networks:
  udalost.net:
    driver: bridge

services:
  ###########
  # service php / apache utilisant un vhost dont le nom est celui de la machine hôte
  #
  #  le service sera accessible à https://docketu.iutnc.univ-lorraine.fr:19043
  ###########

  api.udalost.back:
    image: canals/php:latest
    environment:
      - VHOST_HOSTNAME=docketu.iutnc.univ-lorraine.fr
      - VHOST_DOCROOT=/var/www/back
      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
      - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
    ports:
      - "10080:80"
      - "10043:443"
    volumes:
      - ./backend/backoffice/public:/var/www/back
      - ./backend/backoffice/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - udalost.net
    links:
      - mysql:db

  ###########
  # service php / apache utilisant le vhost par défaut
  #
  #  le service sera accessible à https://docketu.iutnc.univ-lorraine.fr:19143
  ###########
  api.udalost.mobile:
    image: canals/php:latest
    environment:
      - VHOST_HOSTNAME=docketu.iutnc.univ-lorraine.fr
      - VHOST_DOCROOT=/var/www/mobile
      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
      - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
    ports:
      - "10180:80"
      - "10143:443"
    volumes:
      - ./backend/mobileapp/public:/var/www/mobile
      - ./backend/mobileapp/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - udalost.net
    links:
      - mysql:db

    # API web
  api.udalost.web:
    image: canals/php:latest
    environment:
      - VHOST_HOSTNAME=docketu.iutnc.univ-lorraine.fr
      - VHOST_DOCROOT=/var/www/web
      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
      - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
    ports:
      - "10280:80"
      - "10243:443"
    volumes:
      - ./backend/webapp/public:/var/www/web
      - ./backend/webapp/src:/var/www/src
    working_dir: /var/www/src
    networks:
      - udalost.net
    links:
      - mysql:db

  ###############
  #  service apache pour la webapp front
  #  service accessible sur http://docketu.iutnc.univ-lorraine.fr:19280
  ###############

  webfront:
    image: httpd:latest
    environment:
      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
      - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
    ports:
      - "10380:80"
    volumes:
      - ./frontend/public:/usr/local/apache2/htdocs
    working_dir: /usr/local/apache2/htdocs
    networks:
      - udalost.net

  #############################
  # mysql + phpmyadmin
  #############################
  mysql:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=udalost
      - MYSQL_USER=udalost
      - MYSQL_PASSWORD=udalost
      - MYSQL_DATABASE=udalost
    volumes:
      - ./backend/sql:/var/sql
    networks:
      - udalost.net

  ####################################

  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "10480:80"
    links:
      - mysql:db

    networks:
      - udalost.net
